# Generated by Django 6.0 on 2026-01-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='patients', to='api.doctorprofile'),
        ),
    ]
