# Generated by Django 6.0 on 2026-01-09 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_patientprofile_doctor_patientprofile_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('room_type', models.CharField(choices=[('GENERAL', 'General Ward'), ('ICU', 'ICU'), ('PRIVATE', 'Private Room'), ('SEMI', 'Semi-Private Room')], default='GENERAL', max_length=20)),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('scheduled_discharge', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_room', to='api.patientprofile')),
            ],
        ),
    ]
